title: Melissa Putri's Portfolio
description: A collection of my data science projects.
theme: jekyll-theme-minimal

# Social links
social_links:
  github: https://github.com/melissaputri
  linkedin: https://www.linkedin.com/in/melissadiandra/
